### ISSUE TITLE
better Exception information when Retrobuffer fails

### ISSUE THREAD

**Issue by johanvos** [javafxports/javafxmobile-plugin#62] opened 2018-06-03 11:41 UTC
When running ./gradlew androidInstall using Java 9, Retrobuffer might fail. 
The current exception is too cryptic and doesn't provide the developer with a hint:

SEVERE: Failed to run Retrobuffer
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.objectweb.asm.ClassReader.<init>(Unknown Source)
        at org.javafxports.retrobuffer.ClassAnalyzer.analyze(ClassAnalyzer.java:48)
        at org.javafxports.retrobuffer.Retrobuffer$1.visitClass(Retrobuffer.java:59)
        at org.javafxports.retrobuffer.ClasspathVisitor.visitFile(ClasspathVisitor.java:59)
        at org.javafxports.retrobuffer.ClasspathVisitor.visitFile(ClasspathVisitor.java:41)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2713)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2785)
        at org.javafxports.retrobuffer.Retrobuffer.run(Retrobuffer.java:56)
        at org.javafxports.retrobuffer.Main.main(Main.java:45)

It would help providing the file where this exception occurred, and even better it should also print the cause (e.g. wrong major/minor?)

**Comment by tiainen** [comment] 2018-06-05 13:25
Duplicate of #32

**Closed by tiainen** 2018-06-05 13:25 UTC
